spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

springdoc.packagesToScan=com.gajonuco.pecasbr.controller
springdoc.api-docs.enabled=true

telegrambot_chat_id=${TELEGRAM_CHAT_ID}
telegrambot_url=${TELEGRAM_BOT_URL}
telegrambot_msg=Oi Gabriel, tudo bem? Sou eu de novo com boas notícias. Estou aqui para dizer que chegou um novo pedido. O numero dele: %PED%. Para conferir, acesse https://www.projetoreal.dev.br/admin/main/dashboard