jwt.secret=chave-de-teste-super-segura-com-mais-de-32-caracteres
app.public-url=http://localhost:4222

asaas.apikey=asaas-api-key-de-teste
asaas.webhook.token=webhook-token-de-teste

spring.datasource.url=jdbc:mysql://localhost:3306/db_projetoreal
spring.datasource.username=springuser
spring.datasource.password=springpassword