server.port=${SERVER_PORT:8443}
security.require-ssl=true
server.ssl.key-store=${SSL_KEYSTORE_PATH:/etc/letsencrypt/live/projetoreal.dev.br/keystore.p12}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=tomcat

app.public-url=${APP_PUBLIC_URL:https://www.projetoreal.dev.br}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

asaas.url=${ASAAS_URL:https://api.asaas.com/v3}
asaas.apikey=${ASAAS_API_KEY}
asaas.webhook.token=${ASAAS_WEBHOOK_TOKEN}

logging.level.root=WARN
logging.level.org.springframework.web=INFO